### ISSUE TITLE
Correct parameters for docker-compose, how ?

### ISSUE THREAD

**Issue by StefanSa** [cjoergensen/thrifty-elastic-alerting#10]
Hi @cjoergensen Christian,
Thank you for this very interesting project.
Any chance you could explain how to set the correct parameters for docker(-compose) ? i would like to use the tool.

Thanks for your time
StefanS

**Comment by UtopleMan** [comment]
Hey @StefanSa we are in the middle of making the documentation for the project. We will get go this soon

**Comment by cjoergensen** [comment]
@UtopleMan have look at the updated the readme in this branch: https://github.com/cjoergensen/thrifty-elastic-alerting/tree/update-docs

Details about templates, connectors, samples etc are still need. But are we going in the right direction?

**Comment by UtopleMan** [comment]
Docker compose sample setup have been added in samples folder.  You would still need to create the alerting user in Kibana, for this to begin working
